version: '3'
services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./data/backend/static/:/app/data/backend/static/
    env_file:
      - .env
    command: ./entrypoint.sh

  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    restart: on-failure
    volumes:
      - redis_data:/data

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A cybernexvpn.celery.app beat --loglevel=info
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./data/backend/static/:/app/data/backend/static/

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wsgi
    volumes:
      - ./data/backend/static/:/app/data/backend/static/
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot

volumes:
  redis_data:
