version: '3'
services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./data/backend/static/:${STATIC_TARGET_PATH}
    env_file:
      - .env
    command: ./entrypoint.sh

  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    restart: on-failure
    volumes:
      - redis_data:/data

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A nexvpn.celery.app beat --loglevel=info
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./data/backend/static/:${STATIC_TARGET_PATH}

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    depends_on:
      - wsgi
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/backend/static/:${STATIC_TARGET_PATH}
    restart: always
    networks:
      - default

volumes:
  redis_data:

networks:
  default:
