"""
Django settings for cybernexvpn project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import environ
import dj_database_url
from pathlib import Path

from yookassa import Configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

BASE_URL = env.str("BASE_URL", default="http://localhost:8000")

ALLOWED_HOSTS = [
    "www.cybernexvpn.ru",
    "cybernexvpn.ru",
    "localhost",
    "127.0.0.1:8000",
    "127.0.0.1",
    "77.238.236.90",
    "176.124.203.129",
    "176.124.203.129:8000",

    # yookassa
    "185.71.76.0",
    "185.71.77.0",
    "77.75.153.0/25",
    "77.75.156.11",
    "77.75.156.35",
    "77.75.154.128",
    "2a02:5180::/32"
]

CSRF_TRUSTED_ORIGINS = [BASE_URL, "https://www.cybernexvpn.ru", "https://cybernexvpn.ru"]

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_celery_beat",

    "nexvpn",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "cybernexvpn.middleware.YookassaCallbackMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# DRF
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "nexvpn.api.exception_handler.logging_exception_handler",
}

LOG_LEVEL = env.str("LOG_LEVEL", default="INFO").upper()
DJANGO_LOG_LEVEL = env.str("DJANGO_LOG_LEVEL", default="INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime}.{msecs:03.0f} | {levelname:<8} | {name}:{lineno} | {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": env.str("DB_LOG_LEVEL", default="WARNING").upper(),
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.beat": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "cybernexvpn": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "nexvpn": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
# Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'NEX API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'CAMELIZE_NAMES': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENABLE_FILE_UPLOADS': True,

    "AUTHENTICATION_WHITELIST": [],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-KEY",
            }
        }
    },
    "SECURITY": [{"ApiKeyAuth": []}],
}

ROOT_URLCONF = "cybernexvpn.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cybernexvpn.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {"default": dj_database_url.config(default=env.str("DATABASE_URL"))}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "auth.User"
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# CELERY
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", 'redis://redis:6379/1')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = env.str("STATIC_TARGET_PATH", "./data/backend/static/")

BASE_URL = env.str("BASE_URL", "http://localhost:8000")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

YOOKASSA_OAUTH_TOKEN = env.str("YOOKASSA_OAUTH_TOKEN")
Configuration.configure_auth_token(YOOKASSA_OAUTH_TOKEN)

ADMIN_API_KEY = env.str("ADMIN_API_KEY")

TG_BOT_URL = env.str("TG_BOT_URL")
TG_BOT_API_URL = env.str("TG_BOT_API_URL")
TG_BOT_API_KEY = env.str("TG_BOT_API_KEY")

# Remnawave
PANEL_API_URL = env.str("PANEL_API_URL", "https://panel.pineferry.com")
PANEL_API_TOKEN = env.str("PANEL_API_TOKEN", "")
PANEL_API_TIMEOUT = env.int("PANEL_API_TIMEOUT", 15)

# Business Variables
# Длина расчётного периода. Цены тарифов заданы за этот срок, из него же считается
# стоимость дня при смене тарифа. 30, а не «календарный месяц», — чтобы вся
# арифметика оставалась целочисленной и предсказуемой.
DAYS_IN_PERIOD = env.int("DAYS_IN_PERIOD", 30)

# Пробный период для по-настоящему новых пользователей.
TRIAL_DAYS = env.int("TRIAL_DAYS", 3)
TRIAL_PLAN_DEVICES = env.int("TRIAL_PLAN_DEVICES", 3)

# Реферальная программа: обоим начисляется после ПЕРВОЙ оплаты приглашённого.
REFERRAL_INVITER_DAYS = env.int("REFERRAL_INVITER_DAYS", 10)
REFERRAL_INVITEE_DAYS = env.int("REFERRAL_INVITEE_DAYS", 10)

# Миграция старой базы
LEGACY_CUTOFF_DATE = env.str("LEGACY_CUTOFF_DATE", "2026-08-03")
LEGACY_MAX_DEVICES = env.int("LEGACY_MAX_DEVICES", 10)
# Кому на дату среза не досталось ни одного активного устройства: эти уже ушли,
# 30 дней — попытка вернуть.
LEGACY_NO_DEVICES_DAYS = env.int("LEGACY_NO_DEVICES_DAYS", 30)
LEGACY_NO_DEVICES_PLAN_DEVICES = env.int("LEGACY_NO_DEVICES_PLAN_DEVICES", 3)
# Нижний порог. С 3 августа бот фактически не работал, пополниться было негде,
# поэтому у кого период кончился в эти дни — не виноваты и без подписки не остаются.
LEGACY_MIN_DAYS = env.int("LEGACY_MIN_DAYS", 7)
# Потолок на конвертацию, чтобы пара человек с огромным балансом не сидела бесплатно годами.
LEGACY_MAX_DAYS = env.int("LEGACY_MAX_DAYS", 180)
# Аккаунты, которым баланс заливали руками мимо транзакций (свои и друзья): вместо
# конвертации получают условно бесконечную подписку на максимальном тарифе.
# Порог выбран по реальным данным — выше 1000₽ ровно эти шестеро, следующий баланс 850₽.
LEGACY_UNLIMITED_BALANCE = env.int("LEGACY_UNLIMITED_BALANCE", 1000)
LEGACY_UNLIMITED_DAYS = env.int("LEGACY_UNLIMITED_DAYS", 3650)
LEGACY_UNLIMITED_PLAN_DEVICES = env.int("LEGACY_UNLIMITED_PLAN_DEVICES", 10)

# Настройки чека 54-ФЗ живут не здесь, а в модели GlobalSettings — чтобы их
# можно было включить и поправить из админки, когда подключится касса.

SEND_UPDATES_REMINDER_TIME = env.str("SEND_UPDATES_REMINDER_TIME", "10:00")
SEND_UPDATES_TIME = env.str("SEND_UPDATES_TIME", "03:00")
