# Generated by Django 5.1.6 on 2025-02-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестен"),
                    ("android", "Android"),
                    ("iphone", "Iphone"),
                    ("pc", "PC"),
                ],
                default="unknown",
                max_length=31,
            ),
        ),
        migrations.AddField(
            model_name="serverconfig",
            name="ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="client",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endpoint",
                to="nexvpn.client",
            ),
        ),
        migrations.AlterField(
            model_name="nexuser",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
