# Generated by Django 5.1.6 on 2025-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0002_client_type_serverconfig_ssl_alter_endpoint_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.UUIDField(default="1c39b61a-d0a5-40f5-b6f0-7ab576988ecd"),
            preserve_default=False,
        ),
    ]
