# Generated by Django 5.1.6 on 2025-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0003_payment_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидается оплата"),
                    ("succeeded", "Успешный платеж"),
                    ("canceled", "Платеж отменен"),
                ],
                default="pending",
                max_length=31,
            ),
        ),
    ]
