# Generated by Django 5.1.6 on 2025-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0005_remove_payment_status_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_for_capture", "Ожидается оплата"),
                    ("succeeded", "Успешный платеж"),
                    ("failed", "Неуспешный платеж"),
                ],
                default="succeeded",
                max_length=31,
            ),
        ),
    ]
