# Generated by Django 5.1.6 on 2025-03-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0009_promocode_alloweduserpromocode_usedpromocode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocode",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="alloweduserpromocode",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_users",
                to="nexvpn.promocode",
            ),
        ),
    ]
