# Generated by Django 5.1.6 on 2025-03-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0010_rename_active_promocode_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="promo_code",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nexvpn.promocode",
            ),
        ),
    ]
