# Generated by Django 5.1.6 on 2025-03-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0011_transaction_promo_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "subscription_stopped_due_to_lack_of_funds",
                                "Подписка остановлена из-за отсутствия средств на счете",
                            ),
                            (
                                "subscription_stopped_due_to_offed_auto_renew",
                                "Подписка остановлена из-за отключенного автопродления",
                            ),
                            ("renewed", "Подписка продлена"),
                            ("deleted", "Устройство удалено"),
                            ("created", "Устройство добавлено"),
                        ],
                        max_length=63,
                    ),
                ),
                ("automatically", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nexvpn.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexvpn.nexuser"
                    ),
                ),
            ],
        ),
    ]
