# Generated by Django 5.1.6 on 2025-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0012_clientupdates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестен"),
                    ("android", "Android"),
                    ("iphone", "Iphone"),
                    ("windows", "Windows"),
                    ("macos", "MacOS"),
                ],
                default="unknown",
                max_length=31,
            ),
        ),
    ]
