# Generated by Django 5.1.6 on 2025-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0013_alter_client_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="tag",
            field=models.CharField(default="", max_length=31),
            preserve_default=False,
        ),
    ]
