# Generated by Django 5.1.6 on 2025-10-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0014_server_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nexvpn.serverconfig"
            ),
        ),
    ]
