# Generated by Django 5.1.6 on 2025-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexvpn", "0015_alter_server_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="server",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="server",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="server",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userbalance",
            name="value",
            field=models.IntegerField(default=150),
        ),
    ]
