# Generated by Django 5.1.6 on 2025-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nexvpn",
            "0016_alter_server_options_server_order_alter_server_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
