# Generated by Django 5.1.6 on 2026-03-01 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0017_server_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('api_key', models.CharField(max_length=63, unique=True)),
                ('mask_domain', models.CharField(max_length=63)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('renew_subscription', 'Продление подписки'), ('reactivate_clint', 'Возобновление подписки'), ('invitation', 'Приглашение пользователя'), ('start_balance', 'Стартовый баланс'), ('fill_up_balance', 'Пополнение баланса'), ('add_device', 'Добавление устройства'), ('promo_code', 'Применение промокода'), ('updated_by_admin', 'Изменено администратором'), ('add_proxy', 'Добавление прокси'), ('reactivate_proxy_subscription', 'Возобновление подписки на прокси'), ('renew_proxy_subscription', 'Продление подписки на прокси')], max_length=31),
        ),
        migrations.CreateModel(
            name='ProxyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('secret', models.CharField(max_length=63, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nexvpn.nexuser')),
            ],
        ),
    ]
