# Generated by Django 5.1.6 on 2026-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0019_nexuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
