# Generated by Django 5.1.6 on 2026-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0023_drop_wireguard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Бот отвечает заглушкой вместо обычных сценариев. На приём платежей и синхронизацию с панелью не влияет.', verbose_name='Технические работы')),
                ('maintenance_message', models.TextField(default='Ведём технические работы, сервис скоро вернётся. Подписка идёт, ничего не потеряется.', verbose_name='Текст заглушки')),
                ('maintenance_until', models.DateTimeField(blank=True, default=None, help_text='Необязательно. Если указать, бот сможет назвать срок в заглушке.', null=True, verbose_name='Ориентировочно до')),
                ('receipt_enabled', models.BooleanField(default=False, help_text='Включать только когда касса подключена в личном кабинете YooKassa. Пока выключено, email при оплате не спрашивается.', verbose_name='Выписывать чек')),
                ('vat_code', models.PositiveSmallIntegerField(choices=[(1, '1 — без НДС'), (2, '2 — НДС по ставке 0%'), (3, '3 — НДС по пониженной ставке'), (4, '4 — НДС по основной ставке'), (5, '5 — НДС по расчётной пониженной ставке'), (6, '6 — НДС по расчётной основной ставке')], default=1, verbose_name='Ставка НДС')),
                ('payment_subject', models.CharField(choices=[('service', 'Услуга'), ('commodity', 'Товар'), ('work', 'Работа'), ('payment', 'Платёж'), ('another', 'Иное')], default='service', max_length=31, verbose_name='Признак предмета расчёта')),
                ('payment_mode', models.CharField(choices=[('full_payment', 'Полный расчёт'), ('full_prepayment', 'Полная предоплата'), ('partial_prepayment', 'Частичная предоплата'), ('advance', 'Аванс')], default='full_payment', max_length=31, verbose_name='Признак способа расчёта')),
                ('payment_description', models.CharField(default='Оплата подписки CyberNex', help_text='Видно в выписке по карте. Доступны подстановки {devices} и {days}.', max_length=128, verbose_name='Описание платежа')),
                ('purchase_item_template', models.CharField(default='Подписка CyberNex: {devices} устр., {days} дн.', help_text='Подстановки: {devices} — устройств по тарифу, {days} — дней.', max_length=128, verbose_name='Позиция чека — оплата подписки')),
                ('plan_change_item_template', models.CharField(default='Изменение тарифа подписки CyberNex: {devices} устр., {days} дн.', max_length=128, verbose_name='Позиция чека — смена тарифа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
    ]
