# Generated by Django 5.1.6 on 2026-08-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0024_global_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(help_text='На какую дату окончания было напоминание')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='nexvpn.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'hours_before'), name='unique_reminder_per_subscription')],
            },
        ),
    ]
