# Generated by Django 5.1.6 on 2026-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0025_sent_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='maintenance_message',
            field=models.TextField(
                default='Ведём технические работы, сервис скоро вернётся. Подписка идёт, ничего не потеряется.',
                help_text='Показывается всплывающим окном при нажатии кнопок, поэтому без HTML-разметки и не длиннее ~200 символов — Telegram обрежет.',
                verbose_name='Текст заглушки',
            ),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='maintenance_affects_admin',
            field=models.BooleanField(default=False, help_text='По умолчанию администратор (TG_ADMIN_USER_ID) продолжает пользоваться ботом во время техработ — чтобы было чем проверить, что всё починилось. Включите, если нужно посмотреть на заглушку своими глазами.', verbose_name='Заглушка и для админа'),
        ),
    ]
