# Generated by Django 5.1.6 on 2026-08-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0026_maintenance_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnectionWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('known_hwids', models.JSONField(default=list, help_text='Устройства, которые уже были до нажатия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_watch', to='nexvpn.nexuser')),
            ],
        ),
    ]
