# Generated by Django 5.1.6 on 2026-08-10 12:43

from django.db import migrations, models


def seed_periods(apps, schema_editor):
    from nexvpn.subscription.plans import DEFAULT_PERIODS

    BillingPeriod = apps.get_model("nexvpn", "BillingPeriod")
    for months, discount, order in DEFAULT_PERIODS:
        BillingPeriod.objects.get_or_create(
            months=months, defaults={"discount_percent": discount, "order": order}
        )


def noop(apps, schema_editor):
    """Сроки не удаляем: на них могут ссылаться уже показанные людям цены."""


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0027_connection_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(unique=True, verbose_name='Месяцев')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Срок оплаты',
                'verbose_name_plural': 'Сроки оплаты',
                'ordering': ['order', 'months'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='period_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько месяцев оплачено'),
        ),
        migrations.RunPython(seed_periods, noop),
    ]
