# Generated by Django 5.1.6 on 2026-08-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0028_billing_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=63)),
                ('date', models.DateField()),
                ('bytes', models.BigIntegerField(default=0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_usage', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'трафик по ноде за день',
                'verbose_name_plural': 'трафик по нодам',
            },
        ),
        migrations.CreateModel(
            name='UsageDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'использование туннелей',
                'verbose_name_plural': 'Использование туннелей',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nexvpn.nodeusageday',),
        ),
        migrations.CreateModel(
            name='PanelPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_at', models.DateTimeField(blank=True, null=True)),
                ('first_connected_at', models.DateTimeField(blank=True, null=True)),
                ('node_name', models.CharField(blank=True, default='', max_length=63)),
                ('used_traffic', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'присутствие в панели',
                'verbose_name_plural': 'присутствие в панели',
            },
        ),
        migrations.AddIndex(
            model_name='nodeusageday',
            index=models.Index(fields=['date', 'node_name'], name='nexvpn_node_date_e3969c_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodeusageday',
            constraint=models.UniqueConstraint(fields=('user', 'node_name', 'date'), name='unique_user_node_day'),
        ),
    ]
