# Generated by Django 5.1.6 on 2026-08-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0029_nodeusageday_usagedashboard_panelpresence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Для себя, людям не показывается', max_length=120)),
                ('text', models.TextField(help_text="Разметка Telegram: <b>жирный</b>, <i>курсив</i>, <a href='…'>ссылка</a>")),
                ('audience', models.CharField(choices=[('all', 'Все пользователи'), ('legacy_gifted', 'Легаси: без устройств, подарили дни'), ('legacy_converted', 'Легаси: подписка пересчитана'), ('new', 'Пришли уже в новую версию')], default='all', max_length=31)),
                ('with_connect_button', models.BooleanField(default=False, help_text='Ведёт в тот же экран подключения, что и кнопка в меню', verbose_name='Кнопка «Подключиться бесплатно»')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Сорвалась')], default='draft', max_length=15)),
                ('test_only', models.BooleanField(default=False, help_text='Проверочная отправка на TG_ADMIN_USER_ID, остальных не трогаем', verbose_name='Только администратору')),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField()),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='nexvpn.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'доставка рассылки',
                'verbose_name_plural': 'Доставки рассылок',
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'user'), name='unique_broadcast_delivery')],
            },
        ),
    ]
