# Generated by Django 5.1.6 on 2026-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0030_broadcast_broadcastdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='with_menu_button',
            field=models.BooleanField(default=False, help_text='Обе кнопки не правят объявление: снимают с него клавиатуру и присылают экран новым сообщением', verbose_name='Кнопка «В меню»'),
        ),
    ]
