# Generated by Django 5.1.6 on 2026-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0031_broadcast_with_menu_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexuser',
            name='joined_channel',
            field=models.BooleanField(default=False),
        ),
    ]
