# Generated by Django 5.1.6 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0032_nexuser_joined_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(blank=True, choices=[('purchase', 'Оплата периода подписки'), ('plan_change', 'Доплата за смену тарифа'), ('test', 'Проверочный платёж')], default=None, max_length=31, null=True),
        ),
    ]
