# Generated by Django 5.1.6 on 2026-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0033_alter_payment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screen_message_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
