# Generated by Django 5.1.6 on 2026-08-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0034_payment_screen_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='reminders_enabled',
            field=models.BooleanField(default=True, help_text='Выключите, если люди ещё не знают о перезапуске: иначе «осталось 7 дней» прилетит раньше объявления. Сбор статистики и сверка платежей продолжают работать.', verbose_name='Напоминания об окончании подписки'),
        ),
    ]
