# Generated by Django 5.1.6 on 2026-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0035_globalsettings_reminders_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='audience',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('legacy_gifted', 'Легаси: без устройств, подарили дни'), ('legacy_converted', 'Легаси: подписка пересчитана'), ('new', 'Пришли уже в новую версию'), ('not_activated', 'Не заходили в бота после обновления'), ('not_connected', 'Зашли, но ни разу не подключились')], default='all', max_length=31),
        ),
    ]
