# Generated by Django 5.1.6 on 2026-08-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0036_broadcast_not_returned_audiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=63)),
                ('inbound_tag', models.CharField(max_length=63)),
                ('via_relay', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('connections', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_usage', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'туннель по дням',
                'verbose_name_plural': 'Использование по туннелям',
                'indexes': [models.Index(fields=['date', 'inbound_tag'], name='nexvpn_inbo_date_490fca_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'node_name', 'inbound_tag', 'via_relay', 'date'), name='unique_user_inbound_day')],
            },
        ),
    ]
