# Generated by Django 5.1.6 on 2026-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0037_inboundusageday'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='source_chat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='source_message_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
