# Generated by Django 5.1.6 on 2026-09-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0038_broadcast_source_chat_id_broadcast_source_message_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inboundusageday',
            name='unique_user_inbound_day',
        ),
        migrations.AddField(
            model_name='inboundusageday',
            name='asn',
            field=models.PositiveIntegerField(default=0, help_text='Номер автономной системы, 0 — не определилась'),
        ),
        migrations.AddField(
            model_name='inboundusageday',
            name='network',
            field=models.CharField(choices=[('mobile', 'Мобильный'), ('fixed', 'Домашний'), ('unknown', 'Неизвестно')], default='unknown', help_text='Мобильный или домашний — вывод по оператору, не факт от клиента', max_length=15),
        ),
        migrations.AddField(
            model_name='inboundusageday',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='Название сети', max_length=63),
        ),
        migrations.AddIndex(
            model_name='inboundusageday',
            index=models.Index(fields=['date', 'asn'], name='nexvpn_inbo_date_8838bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundusageday',
            constraint=models.UniqueConstraint(fields=('user', 'node_name', 'inbound_tag', 'via_relay', 'date', 'asn'), name='unique_user_inbound_day'),
        ),
    ]
