# Generated by Django 5.1.6 on 2026-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0039_remove_inboundusageday_unique_user_inbound_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayNetworkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('node_name', models.CharField(max_length=63)),
                ('inbound_tag', models.CharField(max_length=63)),
                ('asn', models.PositiveIntegerField(default=0)),
                ('operator', models.CharField(blank=True, default='', max_length=63)),
                ('network', models.CharField(choices=[('mobile', 'Мобильный'), ('fixed', 'Домашний'), ('unknown', 'Неизвестно')], default='unknown', max_length=15)),
                ('connections', models.PositiveIntegerField(default=0)),
                ('clients', models.PositiveIntegerField(default=0, help_text='Разных адресов за сутки')),
            ],
            options={
                'verbose_name': 'релей: сети по дням',
                'verbose_name_plural': 'Релей: сети по дням',
                'indexes': [models.Index(fields=['date', 'inbound_tag'], name='nexvpn_rela_date_e1cd6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'node_name', 'inbound_tag', 'asn'), name='unique_relay_network_day')],
            },
        ),
    ]
