# Generated by Django 5.1.6 on 2026-09-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0040_relaynetworkday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.JSONField(default=list, help_text='HWID, отмеченные на удаление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexvpn.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_selection', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'выбор устройств при смене тарифа',
                'verbose_name_plural': 'Выбор устройств при смене тарифа',
            },
        ),
    ]
