# Generated by Django 5.1.6 on 2026-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0041_planchangeselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='known_device_hwids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
