# Generated by Django 5.1.6 on 2026-09-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0042_subscription_known_device_hwids'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_minutes', models.PositiveIntegerField(help_text='Через сколько минут после первого захода')),
                ('sent', models.BooleanField(default=True, help_text='False — шаг закрыт без отправки')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_nudges', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'подталкивание новичку',
                'verbose_name_plural': 'Подталкивания новичкам',
                'constraints': [models.UniqueConstraint(fields=('user', 'step_minutes'), name='unique_onboarding_nudge_per_user')],
            },
        ),
    ]
