# Generated by Django 5.1.6 on 2026-09-16 12:49

import os

from django.db import migrations, models


def seed_from_env(apps, schema_editor):
    """Перенести действовавшие значения из окружения, а не молча взять дефолт.

    `AddField` уже проставил всем 10 — верно только если `REFERRAL_INVITER_DAYS`/
    `REFERRAL_INVITEE_DAYS` в .env совпадали с дефолтом кода. Читаем окружение
    напрямую (не `django.conf.settings`): к моменту, когда этот деплой накатит
    миграцию, из settings.py эти переменные уже могут быть убраны.
    """
    GlobalSettings = apps.get_model("nexvpn", "GlobalSettings")
    obj, _ = GlobalSettings.objects.get_or_create(pk=1)
    obj.referral_inviter_days = int(os.environ.get("REFERRAL_INVITER_DAYS", 10))
    obj.referral_invitee_days = int(os.environ.get("REFERRAL_INVITEE_DAYS", 10))
    obj.save(update_fields=["referral_inviter_days", "referral_invitee_days"])


def noop(apps, schema_editor):
    """Откатывать нечего: значения просто перестанут быть источником истины."""


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0043_onboardingnudge'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='referral_invitee_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Начисляется приглашённому сверх пробного периода, после его первой оплаты.', verbose_name='Дней приглашённому'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='referral_inviter_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Начисляется тому, кто позвал, после первой оплаты приглашённого.', verbose_name='Дней инвайтеру'),
        ),
        migrations.RunPython(seed_from_env, noop),
    ]
