# Generated by Django 5.1.6 on 2026-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0045_referral_inviter_days_tiered'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='with_referral_buttons',
            field=models.BooleanField(default=False, help_text='«Поделиться ссылкой» и «Скопировать ссылку» — у каждого получателя своя ссылка. «В меню» у такой рассылки снимает только саму себя, кнопки рефералки остаются', verbose_name='Кнопки рефералки'),
        ),
    ]
