# Generated by Django 5.1.6 on 2026-09-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0046_broadcast_with_referral_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='poll_allows_multiple',
            field=models.BooleanField(default=False, verbose_name='Можно выбрать несколько вариантов'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='poll_options',
            field=models.TextField(blank=True, default='', help_text='Заполнено — рассылка уходит опросом, текст выше становится вопросом. Каждый вариант с новой строки, от 2 до 10. Кто за что голосовал — видно здесь, другим пользователям — нет', verbose_name='Варианты ответа'),
        ),
        migrations.AddField(
            model_name='broadcastdelivery',
            name='poll_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='BroadcastPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='nexvpn.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'голос в опросе',
                'verbose_name_plural': 'Голоса в опросах',
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'user'), name='unique_broadcast_poll_vote')],
            },
        ),
    ]
