# Generated by Django 5.1.6 on 2026-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0047_broadcast_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='poll_with_custom',
            field=models.BooleanField(default=False, help_text='Последним добавится вариант «Свой вариант». Кто его выберет, получит просьбу написать ответ; следующее сообщение человека придёт тебе в личку от бота, ответить можно реплаем, как в поддержке', verbose_name='Свой вариант'),
        ),
        migrations.AddField(
            model_name='broadcastpollvote',
            name='custom_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('awaiting', 'ждём ответ'), ('answered', 'ответил'), ('declined', 'отказался')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='broadcastpollvote',
            name='custom_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
