# Generated by Django 5.1.6 on 2026-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0048_broadcast_poll_custom_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='user_ids',
            field=models.TextField(blank=True, default='', help_text='Для аудитории «Конкретные пользователи»: Telegram id через пробел, запятую или с новой строки', verbose_name='id получателей'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='audience',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('legacy_gifted', 'Легаси: без устройств, подарили дни'), ('legacy_converted', 'Легаси: подписка пересчитана'), ('new', 'Пришли уже в новую версию'), ('not_activated', 'Не заходили в бота после обновления'), ('not_connected', 'Зашли, но ни разу не подключились'), ('specific', 'Конкретные пользователи (по id)')], default='all', max_length=31),
        ),
    ]
