# Generated by Django 5.1.6 on 2026-09-22 11:17

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0049_broadcast_specific_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Его видит человек: «Цены отображаются с учетом скидки по промокоду «…»». Это не сам код', max_length=120, verbose_name='Название')),
                ('kind', models.CharField(choices=[('code', 'Промокод (ввод кода)'), ('verification', 'С подтверждением (заявка → админ)')], default='code', max_length=15, verbose_name='Вид')),
                ('code', models.CharField(blank=True, default='', help_text='Только для промокода: латиница и цифры, 3–32 символа (так работает ссылка). Регистр не важен', max_length=32, verbose_name='Код')),
                ('valid_until', models.DateTimeField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включена')),
                ('is_public', models.BooleanField(default=True, help_text='Выключено — применить могут только пользователи из списка id ниже', verbose_name='Доступна всем')),
                ('user_ids', models.TextField(blank=True, default='', help_text='Для недоступной всем: Telegram id через пробел, запятую или с новой строки', verbose_name='id пользователей')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Для скидки с подтверждением: кнопка с её названием в разделе меню', verbose_name='Кнопка в «Промокоды и скидки»')),
                ('verification_prompt', models.TextField(blank=True, default='', help_text='Для скидки с подтверждением: текст после нажатия на кнопку', verbose_name='Что попросить прислать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'скидка / промокод',
                'verbose_name_plural': 'Скидки и промокоды',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), condition=models.Q(('code', ''), _negated=True), name='unique_discount_code_ci')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='nexvpn.discount'),
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_month', models.PositiveIntegerField(verbose_name='Цена за 30 дней, ₽')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='nexvpn.discount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexvpn.plan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'цена по скидке',
                'verbose_name_plural': 'Цены по скидке',
                'constraints': [models.UniqueConstraint(fields=('discount', 'plan'), name='unique_discount_plan_price')],
            },
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('active', 'Действует'), ('rejected', 'Отклонена'), ('replaced', 'Заменена другой')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='nexvpn.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'скидка пользователя',
                'verbose_name_plural': 'Скидки пользователей',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'discount'), name='unique_pending_user_discount')],
            },
        ),
    ]
