# Generated by Django 5.1.6 on 2026-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0051_student_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Только для надписи на кнопках с ценой: 50 → «-50%✅». Цены берутся из таблицы ниже. Пусто — без надписи', max_length=10, verbose_name='Скидка'),
        ),
    ]
