# Generated by Django 5.1.6 on 2026-09-22 13:12

from django.db import migrations, models


def mark_requests(apps, schema_editor):
    """Уже выданные скидки с подтверждением получены заявкой, а не кодом."""
    UserDiscount = apps.get_model("nexvpn", "UserDiscount")
    UserDiscount.objects.filter(discount__kind="verification").update(via="request")


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0053_cu_student_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='via',
            field=models.CharField(choices=[('code', 'По коду'), ('request', 'По заявке')], default='code', max_length=10, verbose_name='Как получена'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Латиница и цифры, 3–32 символа (так работает ссылка), регистр не важен. У промокода обязателен; у скидки с подтверждением — по желанию: с ним скидку можно получить и кодом, и заявкой', max_length=32, verbose_name='Код'),
        ),
        migrations.RunPython(mark_requests, migrations.RunPython.noop),
    ]
