# Generated by Django 5.1.6 on 2026-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0055_code_only_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscount',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('active', 'Действует'), ('rejected', 'Отклонена'), ('replaced', 'Заменена другой'), ('revoked', 'Снята администратором')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='via',
            field=models.CharField(choices=[('code', 'Сам: по коду'), ('request', 'Сам: по заявке'), ('admin', 'Назначена администратором')], default='code', max_length=10, verbose_name='Как получена'),
        ),
    ]
