# Generated by Django 5.1.6 on 2026-09-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0056_discount_admin_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='название')),
                ('provider', models.CharField(blank=True, default='', max_length=63, verbose_name='хостер')),
                ('address', models.CharField(blank=True, default='', max_length=127, verbose_name='адрес или домен')),
                ('country', models.CharField(blank=True, default='', max_length=63, verbose_name='страна')),
                ('city', models.CharField(blank=True, default='', max_length=63, verbose_name='город')),
                ('role', models.CharField(choices=[('exit_abroad', 'Выход за рубеж'), ('relay_ru', 'Российский вход-релей'), ('exit_ru', 'Российский выход'), ('panel', 'Панель'), ('app', 'Прод (бот и сайт)'), ('sub_mirror', 'Зеркало подписки'), ('other', 'Прочее')], default='exit_abroad', max_length=16, verbose_name='роль')),
                ('traffic_limit_tb', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — безлимит', max_digits=7, null=True, verbose_name='лимит трафика, ТБ')),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена в месяц')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('EUR', '€'), ('USD', '$')], default='RUB', max_length=3, verbose_name='валюта')),
                ('renew_at', models.DateField(blank=True, null=True, verbose_name='продлить до')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='автопродление')),
                ('is_active', models.BooleanField(default=True, verbose_name='используется')),
                ('panel_node_name', models.CharField(blank=True, default='', help_text='Как нода называется в Remnawave, например de1-ovh. Пусто — сервер не нода.', max_length=63, verbose_name='нода в панели')),
                ('note', models.TextField(blank=True, default='', verbose_name='заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServerCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='за что')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('EUR', '€'), ('USD', '$')], default='RUB', max_length=3, verbose_name='валюта')),
                ('kind', models.CharField(choices=[('once', 'Разовый'), ('month', 'Ежемесячный'), ('year', 'Ежегодный')], default='month', max_length=8, verbose_name='периодичность')),
                ('happened_on', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('note', models.TextField(blank=True, default='', verbose_name='заметка')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='nexvpn.server')),
            ],
            options={
                'verbose_name': 'расход по серверу',
                'verbose_name_plural': 'Расходы по серверам',
                'ordering': ['server', 'title'],
            },
        ),
    ]
