# Generated by Django 5.1.6 on 2026-09-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0058_seed_servers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('exit_node', models.CharField(help_text='Имя ноды в панели', max_length=63, verbose_name='выход')),
                ('entry', models.CharField(choices=[('atlex', 'Atlex (Россия)'), ('timeweb', 'Timeweb (Россия)'), ('eurobyte_a', 'EuroByte (Россия)'), ('eurobyte_b', 'EuroByte 2 (Россия)'), ('direct', 'Напрямую, без прослойки')], max_length=16, verbose_name='вход')),
                ('protocol', models.CharField(max_length=24, verbose_name='протокол')),
                ('bytes_in', models.BigIntegerField(default=0, verbose_name='принято')),
                ('bytes_out', models.BigIntegerField(default=0, verbose_name='отдано')),
                ('connections', models.PositiveIntegerField(default=0, verbose_name='соединений')),
                ('probes', models.PositiveIntegerField(default=0, verbose_name='проб автовыбора')),
                ('users', models.JSONField(blank=True, default=list, verbose_name='кто качал')),
                ('probing', models.JSONField(blank=True, default=list, verbose_name='кто только щупал')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'связка за сутки',
                'verbose_name_plural': 'Связки: трафик и люди',
                'ordering': ['-date', 'exit_node', 'entry', 'protocol'],
                'indexes': [models.Index(fields=['-date', 'exit_node'], name='nexvpn_link_date_b821bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'exit_node', 'entry', 'protocol'), name='unique_link_usage_day')],
            },
        ),
    ]
