# Generated by Django 5.1.6 on 2026-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0059_link_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_host_override',
            field=models.CharField(blank=True, default='', help_text='Например sub.cybernexapp.com. Пусто — как в панели.', max_length=127, verbose_name='выдавать на хосте'),
        ),
    ]
