# Generated by Django 5.1.6 on 2026-09-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexvpn', '0060_sub_host_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHostProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.CharField(max_length=127, verbose_name='адрес выдачи')),
                ('outcome', models.CharField(choices=[('ok', 'Ответил'), ('slow', 'Ответил, но медленно'), ('failed', 'Не ответил')], max_length=8, verbose_name='исход')),
                ('ms', models.PositiveIntegerField(default=0, verbose_name='миллисекунд')),
                ('short_uuid', models.CharField(blank=True, default='', max_length=63)),
                ('platform', models.CharField(blank=True, default='', max_length=31)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_probes', to='nexvpn.nexuser')),
            ],
            options={
                'verbose_name': 'проба адреса подписки',
                'verbose_name_plural': 'Пробы адресов подписки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'host'], name='nexvpn_subh_created_f83ec7_idx')],
            },
        ),
    ]
